package edu.sizetron.jftp;

public enum FTPState {
	USER_SEND,
	PASS_SEND,
	CWD_SEND,
	CDUP_SEND,
	QUIT_SEND,
	PASV_SEND,
	EPSV_SEND,
	PORT_SEND,
	EPRT_SEND,
	RETR_SEND,
	PWD_SEND,
	LIST_SEND,
	HELP_SEND,
	AWAITING_COMMAND,
	AWAITING_RESPONSE,
	POSITIVE_PRELIM_REPLY_RECVD,
	POSITIVE_COMP_REPLY_RECVD,
	POSITIVE_INTER_REPLY_RECVD,
	NEGATIVE_TRANS_REPLY_RECVD,
	NEGATIVE_PERM_REPLY_RECVD,
	NET_ERROR
}
